
server:
  port: 8080

spring:
  flyway:
    enable: true
    baseline-on-migrate: true
    schemas: qrcode
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: qrcode
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:h2:mem:qrcode_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
  messages:
    basename: classpath:messages
    encoding: UTF-8

qrcode:
  immediate:
    expiration-days: 2

logging:
  level:
    root: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%22([%.20t]) %-5level %logger{36}: %X %msg) %n %ex{full}"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %22([%.20t]) %-5level %logger{36}: %X %msg %n %ex{full}"
